; [env:nano328]
; platform = atmelavr
; board = nanoatmega328      ; old bootloader
; ; board = nanoatmega328new   ; с новым загрузчиком
; framework = arduino
[env:mhetesp32devkit]
platform  = espressif32
board     = mhetesp32devkit
framework = arduino



monitor_speed = 115200
lib_deps =
