    [env:esp32doit-devkit-v1]
    platform = espressif32
    board = esp32doit-devkit-v1
    framework = arduino


    ; [env:esp32dev]
    ; platform = espressif32
    ; board = esp32dev
    ;  framework = arduino


    ; [env:esp32-s3-devkitc-1]
    ; platform = espressif32
    ; board = esp32-s3-devkitc-1


    ;  framework = arduino
    ; upload_port = COM13
    ; monitor_port = COM13
    upload_speed = 921600
    monitor_speed = 115200
    lib_deps = 
        ; https://github.com/LSatan/SmartRC-CC1101-Driver-Lib   
        ; lib/GyverWire-main.zip
        ; lib/rc-switch-master.zip
        ; lib/RadioHead-1.145.zip
        ; gyverlibs/GyverWire@^1.1.4  
        ; ; sui77/rc-switch@^2.6.4